export const LOAD_LINKS = 'LOAD_LINKS'
export const LINKS_LOADED = 'LINKS_LOADED'
export const ADD_LINK = 'ADD_LINK'
export const REMOVE_LINK = 'REMOVE_LINK'
export const LINK_REMOVED_SUCCESSFULLY = 'LINK_REMOVED_SUCCESSFULLY'

export const ADD_TAG = 'ADD_TAG'
export const REMOVE_TAG = 'REMOVE_TAG'
export const TAG_REMOVED_SUCCESSFULLY = 'TAG_REMOVED_SUCCESSFULLY'

export const TOGGLE_ARCHIVE = 'TOGGLE_ARCHIVE'
export const SEARCH_BY_TEXT = 'SEARCH_BY_TEXT'

export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGOUT = 'LOGOUT'
